trigger:
  - main

pool:
  name: 'agent'  # Your self-hosted agent pool name

steps:
  - task: Maven@3
    displayName: 'Maven Build and Regression Test'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean test'
      publishJUnitResults: true
      testResultsFiles: '**/target/surefire-reports/TEST-*.xml'